"""followers

Revision ID: 354f7e091cce
Revises: 2038cf20d836
Create Date: 2020-02-18 20:54:01.307813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354f7e091cce'
down_revision = '2038cf20d836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.drop_column('user', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('content', sa.TEXT(), nullable=True))
    op.drop_table('followers')
    # ### end Alembic commands ###
